name: Metrics
on:
  # Se actualiza cada hora
  schedule: [{cron: "0 * * * *"}]
  # Permite ejecutarlo manualmente
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # --- CONFIGURACIÓN VISUAL ---
          user: NamelessVamp
          template: classic
          base: header, activity, community, repositories
          config_timezone: America/Mexico_City
          
          # ESTO ACTIVA EL MODO OSCURO
          config_theme: dark
          
          # Calendario Isométrico
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
