name: Metrics
on:
  # Schedule updates (cada hora)
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          # Tu token secreto
          token: ${{ secrets.METRICS_TOKEN }}
          
          # Opciones base
          user: NamelessVamp
          template: classic
          base: header, activity, community, repositories
          
          # El calendario isom√©trico (Estilo Simon Lecoq)
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
